/**
 * Fix Script: 36_update_find_expert.js
 * Purpose: Update Find Expert widget to use name-based skill search (deduped)
 *          and average scores across categories for multi-category skills
 *
 * Changes:
 *   SERVER: Search by skill name instead of sys_id. For each user, group their
 *           matching skills by name, average proficiency across categories, and
 *           show category breadcrumbs. Scoring uses averaged proficiency.
 *   TEMPLATE: Replace sn-record-picker with custom typeahead (same pattern as
 *             Add Skill modal). Show category sub-entries per skill in results.
 *   CLIENT: Typeahead search, chip-based skill selection, endorse per entry.
 *
 * Run via: Scripts - Background (Global scope)
 */
(function() {
    try {
        gs.info('[Skills Hub] ===== STARTING 36_update_find_expert =====');

        var widgetGR = new GlideRecord('sp_widget');
        widgetGR.addQuery('name', 'CONTAINS', 'Find Expert');
        widgetGR.query();
        if (!widgetGR.next()) {
            gs.error('[Skills Hub] Find Expert widget not found. Aborting.');
            return;
        }
        var widgetId = widgetGR.getUniqueValue();
        var widgetName = widgetGR.getValue('name');
        gs.info('[Skills Hub] Found widget: ' + widgetName + ' sys_id=' + widgetId);

        // ============================================================
        // 1. Replace SERVER SCRIPT
        // ============================================================
        var newServer = '(function() {\n'
            + '  var SCORE_MUST_HAVE = 20;\n'
            + '  var SCORE_NICE_HAVE = 5;\n'
            + '  var MULTIPLIER_EXPERT = 1.5;\n'
            + '  var MULTIPLIER_ADVANCED = 1.2;\n'
            + '\n'
            + '  // --- SEARCH SKILLS (typeahead, deduplicated by name) ---\n'
            + '  if (input && input.action == "searchSkills") {\n'
            + '      var term = (input.term || "").toLowerCase();\n'
            + '      var seen = {};\n'
            + '      var results = [];\n'
            + '      if (term.length >= 2) {\n'
            + '          var sg = new GlideRecord("cmn_skill");\n'
            + '          sg.addQuery("name", "CONTAINS", term);\n'
            + '          sg.orderBy("name");\n'
            + '          sg.setLimit(200);\n'
            + '          sg.query();\n'
            + '          while (sg.next()) {\n'
            + '              var sName = sg.getValue("name");\n'
            + '              if (!seen[sName]) {\n'
            + '                  seen[sName] = true;\n'
            + '                  results.push(sName);\n'
            + '              }\n'
            + '          }\n'
            + '      }\n'
            + '      data.skillSuggestions = results;\n'
            + '  }\n'
            + '\n'
            + '  // --- Helper: resolve category path for a cmn_skill ---\n'
            + '  function getCategoryPath(skillSysId) {\n'
            + '      var m2m = new GlideRecord("cmn_skill_m2m_category");\n'
            + '      m2m.addQuery("skill", skillSysId);\n'
            + '      m2m.setLimit(1);\n'
            + '      m2m.query();\n'
            + '      if (m2m.next()) {\n'
            + '          var cId = m2m.getValue("category");\n'
            + '          var cGR = new GlideRecord("cmn_skill_category");\n'
            + '          if (cGR.get(cId)) {\n'
            + '              var path = cGR.getValue("name");\n'
            + '              var pRef = cGR.getValue("parent");\n'
            + '              var d = 0;\n'
            + '              while (pRef && d < 5) {\n'
            + '                  var pGR = new GlideRecord("cmn_skill_category");\n'
            + '                  if (pGR.get(pRef)) {\n'
            + '                      path = pGR.getValue("name") + " > " + path;\n'
            + '                      pRef = pGR.getValue("parent");\n'
            + '                  } else break;\n'
            + '                  d++;\n'
            + '              }\n'
            + '              return path;\n'
            + '          }\n'
            + '      }\n'
            + '      return "";\n'
            + '  }\n'
            + '\n'
            + '  // --- Helper: parse proficiency level to number ---\n'
            + '  function levelToInt(levelStr) {\n'
            + '      if (levelStr.indexOf("Expert") > -1) return 5;\n'
            + '      if (levelStr.indexOf("Advanced") > -1) return 4;\n'
            + '      if (levelStr.indexOf("Proficient") > -1) return 3;\n'
            + '      if (levelStr.indexOf("Intermediate") > -1 || levelStr.indexOf("Learner") > -1) return 2;\n'
            + '      return 1;\n'
            + '  }\n'
            + '\n'
            + '  // --- SEARCH EXPERTS BY SKILL NAMES ---\n'
            + '  if (input && input.action == "search") {\n'
            + '      var mustNames = input.mustHave ? input.mustHave.split(",") : [];\n'
            + '      var niceNames = input.niceHave ? input.niceHave.split(",") : [];\n'
            + '      var allNames = mustNames.concat(niceNames);\n'
            + '\n'
            + '      // Find ALL cmn_skill sys_ids for each skill name\n'
            + '      var nameToIds = {};\n'
            + '      if (allNames.length > 0) {\n'
            + '          var skillGR = new GlideRecord("cmn_skill");\n'
            + '          skillGR.addQuery("name", "IN", allNames.join(","));\n'
            + '          skillGR.query();\n'
            + '          while (skillGR.next()) {\n'
            + '              var nm = skillGR.getValue("name");\n'
            + '              if (!nameToIds[nm]) nameToIds[nm] = [];\n'
            + '              nameToIds[nm].push(skillGR.getUniqueValue());\n'
            + '          }\n'
            + '      }\n'
            + '\n'
            + '      // Collect all skill sys_ids\n'
            + '      var allSkillIds = [];\n'
            + '      var skillIdToName = {};\n'
            + '      for (var sn in nameToIds) {\n'
            + '          for (var i = 0; i < nameToIds[sn].length; i++) {\n'
            + '              allSkillIds.push(nameToIds[sn][i]);\n'
            + '              skillIdToName[nameToIds[sn][i]] = sn;\n'
            + '          }\n'
            + '      }\n'
            + '\n'
            + '      var users = {};\n'
            + '      if (allSkillIds.length > 0) {\n'
            + '          var gr = new GlideRecord("sys_user_has_skill");\n'
            + '          gr.addQuery("skill", "IN", allSkillIds.join(","));\n'
            + '          gr.addQuery("user.active", true);\n'
            + '          gr.query();\n'
            + '\n'
            + '          while (gr.next()) {\n'
            + '              var uid = gr.user.toString();\n'
            + '              var skillId = gr.skill.toString();\n'
            + '              var skillNm = skillIdToName[skillId] || gr.skill.name.toString();\n'
            + '              var levelStr = gr.skill_level.toString();\n'
            + '              var levelInt = levelToInt(levelStr);\n'
            + '              var catPath = getCategoryPath(skillId);\n'
            + '\n'
            + '              if (!users[uid]) {\n'
            + '                  users[uid] = {\n'
            + '                      sys_id: uid,\n'
            + '                      name: gr.user.name.toString(),\n'
            + '                      title: gr.user.title.toString() || "Employee",\n'
            + '                      skillGroups: {},\n'
            + '                      rawScore: 0,\n'
            + '                      mustHits: 0\n'
            + '                  };\n'
            + '              }\n'
            + '\n'
            + '              // Group entries by skill name\n'
            + '              if (!users[uid].skillGroups[skillNm]) {\n'
            + '                  users[uid].skillGroups[skillNm] = {\n'
            + '                      name: skillNm,\n'
            + '                      entries: [],\n'
            + '                      isMust: (mustNames.indexOf(skillNm) > -1)\n'
            + '                  };\n'
            + '                  if (users[uid].skillGroups[skillNm].isMust) users[uid].mustHits++;\n'
            + '              }\n'
            + '\n'
            + '              users[uid].skillGroups[skillNm].entries.push({\n'
            + '                  skill_record_id: gr.getUniqueValue(),\n'
            + '                  skill_sys_id: skillId,\n'
            + '                  category_path: catPath,\n'
            + '                  level_value: levelInt,\n'
            + '                  level_display: levelStr,\n'
            + '                  endorsements: parseInt(gr.u_peer_endorsement_count.toString() || "0")\n'
            + '              });\n'
            + '          }\n'
            + '      }\n'
            + '\n'
            + '      // Build results with averaged scores\n'
            + '      var matches = [];\n'
            + '      var maxPossible = (mustNames.length * (SCORE_MUST_HAVE * MULTIPLIER_EXPERT))\n'
            + '                      + (niceNames.length * (SCORE_NICE_HAVE * MULTIPLIER_EXPERT));\n'
            + '      if (maxPossible == 0) maxPossible = 100;\n'
            + '\n'
            + '      for (var id in users) {\n'
            + '          var u = users[id];\n'
            + '          var skills = [];\n'
            + '          u.rawScore = 0;\n'
            + '\n'
            + '          for (var sName in u.skillGroups) {\n'
            + '              var sg = u.skillGroups[sName];\n'
            + '              // Average proficiency across categories\n'
            + '              var totalLevel = 0;\n'
            + '              for (var e = 0; e < sg.entries.length; e++) {\n'
            + '                  totalLevel += sg.entries[e].level_value;\n'
            + '              }\n'
            + '              var avgLevel = totalLevel / sg.entries.length;\n'
            + '\n'
            + '              // Score based on averaged level\n'
            + '              var points = sg.isMust ? SCORE_MUST_HAVE : SCORE_NICE_HAVE;\n'
            + '              if (avgLevel >= 5) points *= MULTIPLIER_EXPERT;\n'
            + '              else if (avgLevel >= 4) points *= MULTIPLIER_ADVANCED;\n'
            + '              u.rawScore += points;\n'
            + '\n'
            + '              skills.push({\n'
            + '                  name: sName,\n'
            + '                  avg_level: Math.round(avgLevel * 10) / 10,\n'
            + '                  entry_count: sg.entries.length,\n'
            + '                  entries: sg.entries,\n'
            + '                  isMust: sg.isMust\n'
            + '              });\n'
            + '          }\n'
            + '\n'
            + '          var matchPct = Math.min(Math.round((u.rawScore / maxPossible) * 100), 100);\n'
            + '          var names = u.name.split(" ");\n'
            + '          var initials = (names[0][0] + (names.length > 1 ? names[names.length-1][0] : "")).toUpperCase();\n'
            + '\n'
            + '          matches.push({\n'
            + '              id: u.sys_id,\n'
            + '              name: u.name,\n'
            + '              title: u.title,\n'
            + '              initials: initials,\n'
            + '              skills: skills,\n'
            + '              matchScore: matchPct,\n'
            + '              availability: "high"\n'
            + '          });\n'
            + '      }\n'
            + '\n'
            + '      matches.sort(function(a, b) { return b.matchScore - a.matchScore; });\n'
            + '      data.matches = matches;\n'
            + '  }\n'
            + '\n'
            + '  // --- ENDORSE ACTION ---\n'
            + '  if (input && input.action == "endorse") {\n'
            + '     var endorser = gs.getUserID();\n'
            + '     var skillRecId = input.skill_record_id;\n'
            + '     data.endorsed = false;\n'
            + '     data.endorseError = "";\n'
            + '\n'
            + '     if (!skillRecId) {\n'
            + '        data.endorseError = "No skill record specified.";\n'
            + '     } else {\n'
            + '        var skillRec = new GlideRecord("sys_user_has_skill");\n'
            + '        if (!skillRec.get(skillRecId)) {\n'
            + '           data.endorseError = "Skill record not found.";\n'
            + '        } else {\n'
            + '           var skillOwner = skillRec.user.toString();\n'
            + '           if (endorser == skillOwner) {\n'
            + '              data.endorseError = "You cannot endorse your own skill.";\n'
            + '           } else {\n'
            + '              var dup = new GlideRecord("u_m2m_skill_endorsement");\n'
            + '              dup.addQuery("u_endorser", endorser);\n'
            + '              dup.addQuery("u_skill_record", skillRecId);\n'
            + '              dup.query();\n'
            + '              if (dup.hasNext()) {\n'
            + '                 data.endorseError = "You have already endorsed this skill.";\n'
            + '              } else {\n'
            + '                 var endRec = new GlideRecord("u_m2m_skill_endorsement");\n'
            + '                 endRec.initialize();\n'
            + '                 endRec.u_endorser = endorser;\n'
            + '                 endRec.u_skill_record = skillRecId;\n'
            + '                 var newId = endRec.insert();\n'
            + '                 if (newId) {\n'
            + '                    data.endorsed = true;\n'
            + '                 } else {\n'
            + '                    data.endorseError = "Failed to create endorsement record.";\n'
            + '                 }\n'
            + '              }\n'
            + '           }\n'
            + '        }\n'
            + '     }\n'
            + '  }\n'
            + '})();\n';

        widgetGR = new GlideRecord('sp_widget');
        widgetGR.get(widgetId);
        widgetGR.setValue('script', newServer);
        widgetGR.update();
        gs.info('[Skills Hub] Server script replaced with name-based search + averaged scoring');

        // ============================================================
        // 2. Replace TEMPLATE
        // ============================================================
        widgetGR = new GlideRecord('sp_widget');
        widgetGR.get(widgetId);
        var oldTemplate = widgetGR.getValue('template') || '';
        gs.info('[Skills Hub] Old template length: ' + oldTemplate.length);

        var newTemplate = ''
            + '<div class="skills-find-expert">\n'
            + '  <div class="panel panel-default">\n'
            + '    <div class="panel-heading">\n'
            + '      <h3 class="panel-title"><i class="fa fa-search"></i> Find Expert</h3>\n'
            + '    </div>\n'
            + '    <div class="panel-body">\n'
            + '\n'
            + '      <!-- MUST-HAVE Skills -->\n'
            + '      <div class="form-group">\n'
            + '        <label>Must-Have Skills</label>\n'
            + '        <div style="position:relative;">\n'
            + '          <input type="text" class="form-control" placeholder="Type to search skills..."\n'
            + '                 ng-model="c.mustInput" ng-change="c.typeaheadSearch(\'must\')" />\n'
            + '          <div class="typeahead-dropdown" ng-if="c.mustSuggestions.length > 0">\n'
            + '            <div class="typeahead-item" ng-repeat="s in c.mustSuggestions"\n'
            + '                 ng-click="c.selectSkill(\'must\', s)">{{s}}</div>\n'
            + '          </div>\n'
            + '        </div>\n'
            + '        <div class="chip-list" ng-if="c.mustChips.length > 0">\n'
            + '          <span class="skill-chip" ng-repeat="chip in c.mustChips">\n'
            + '            {{chip}} <i class="fa fa-times" ng-click="c.removeChip(\'must\', $index)"></i>\n'
            + '          </span>\n'
            + '        </div>\n'
            + '      </div>\n'
            + '\n'
            + '      <!-- NICE-TO-HAVE Skills -->\n'
            + '      <div class="form-group">\n'
            + '        <label>Nice-to-Have Skills</label>\n'
            + '        <div style="position:relative;">\n'
            + '          <input type="text" class="form-control" placeholder="Type to search skills..."\n'
            + '                 ng-model="c.niceInput" ng-change="c.typeaheadSearch(\'nice\')" />\n'
            + '          <div class="typeahead-dropdown" ng-if="c.niceSuggestions.length > 0">\n'
            + '            <div class="typeahead-item" ng-repeat="s in c.niceSuggestions"\n'
            + '                 ng-click="c.selectSkill(\'nice\', s)">{{s}}</div>\n'
            + '          </div>\n'
            + '        </div>\n'
            + '        <div class="chip-list" ng-if="c.niceChips.length > 0">\n'
            + '          <span class="skill-chip nice" ng-repeat="chip in c.niceChips">\n'
            + '            {{chip}} <i class="fa fa-times" ng-click="c.removeChip(\'nice\', $index)"></i>\n'
            + '          </span>\n'
            + '        </div>\n'
            + '      </div>\n'
            + '\n'
            + '      <button class="btn btn-primary" ng-click="c.search()"\n'
            + '              ng-disabled="c.mustChips.length == 0 && c.niceChips.length == 0">\n'
            + '        <i class="fa fa-search"></i> Search Experts\n'
            + '      </button>\n'
            + '\n'
            + '      <!-- Loading -->\n'
            + '      <div ng-if="c.loading" class="text-center" style="padding:30px;">\n'
            + '        <i class="fa fa-spinner fa-spin fa-2x"></i>\n'
            + '      </div>\n'
            + '\n'
            + '      <!-- No Results -->\n'
            + '      <div ng-if="c.searched && !c.loading && c.results.length == 0" class="text-center" style="padding:30px;">\n'
            + '        <p class="text-muted">No experts found matching your criteria.</p>\n'
            + '      </div>\n'
            + '\n'
            + '      <!-- Results -->\n'
            + '      <div class="results-grid" ng-if="c.results.length > 0">\n'
            + '        <div class="expert-card" ng-repeat="expert in c.results">\n'
            + '          <div class="expert-header">\n'
            + '            <div class="avatar-circle">{{expert.initials}}</div>\n'
            + '            <div class="expert-info">\n'
            + '              <div class="expert-name">{{expert.name}}</div>\n'
            + '              <div class="expert-title">{{expert.title}}</div>\n'
            + '            </div>\n'
            + '            <div class="match-score" ng-class="c.getScoreClass(expert.matchScore)">\n'
            + '              {{expert.matchScore}}%\n'
            + '            </div>\n'
            + '          </div>\n'
            + '\n'
            + '          <!-- Grouped skills -->\n'
            + '          <div class="expert-skills">\n'
            + '            <div class="skill-group-row" ng-repeat="sg in expert.skills">\n'
            + '              <div class="sg-header">\n'
            + '                <span class="sg-name" ng-class="{\'sg-must\': sg.isMust}">{{sg.name}}</span>\n'
            + '                <span class="sg-avg">Avg: {{sg.avg_level}}/5</span>\n'
            + '                <span class="badge" ng-if="sg.entry_count > 1"\n'
            + '                      style="font-size:10px; background:#e2e8f0; color:#64748b; margin-left:4px;">\n'
            + '                  {{sg.entry_count}} categories\n'
            + '                </span>\n'
            + '              </div>\n'
            + '              <!-- Category sub-entries -->\n'
            + '              <div class="sg-entries" ng-if="sg.entry_count > 1">\n'
            + '                <div class="sg-entry" ng-repeat="ent in sg.entries">\n'
            + '                  <span class="sg-cat-path">{{ent.category_path}}</span>\n'
            + '                  <span class="sg-level">{{ent.level_display || ("Level " + ent.level_value)}}</span>\n'
            + '                  <span class="endorsement-pill" ng-if="ent.endorsements > 0">\n'
            + '                    <i class="fa fa-thumbs-up"></i> {{ent.endorsements}}\n'
            + '                  </span>\n'
            + '                  <button class="btn btn-xs btn-default" ng-click="c.endorse(expert, ent)"\n'
            + '                          title="Endorse this skill">\n'
            + '                    <i class="fa fa-thumbs-up"></i>\n'
            + '                  </button>\n'
            + '                </div>\n'
            + '              </div>\n'
            + '              <!-- Single category: inline -->\n'
            + '              <div class="sg-entries" ng-if="sg.entry_count == 1">\n'
            + '                <div class="sg-entry">\n'
            + '                  <span class="sg-cat-path">{{sg.entries[0].category_path}}</span>\n'
            + '                  <span class="sg-level">{{sg.entries[0].level_display || ("Level " + sg.entries[0].level_value)}}</span>\n'
            + '                  <span class="endorsement-pill" ng-if="sg.entries[0].endorsements > 0">\n'
            + '                    <i class="fa fa-thumbs-up"></i> {{sg.entries[0].endorsements}}\n'
            + '                  </span>\n'
            + '                  <button class="btn btn-xs btn-default" ng-click="c.endorse(expert, sg.entries[0])"\n'
            + '                          title="Endorse this skill">\n'
            + '                    <i class="fa fa-thumbs-up"></i>\n'
            + '                  </button>\n'
            + '                </div>\n'
            + '              </div>\n'
            + '            </div>\n'
            + '          </div>\n'
            + '        </div>\n'
            + '      </div>\n'
            + '\n'
            + '    </div>\n'
            + '  </div>\n'
            + '</div>\n';

        widgetGR.setValue('template', newTemplate);
        widgetGR.update();
        gs.info('[Skills Hub] Template replaced with typeahead + grouped results');

        // ============================================================
        // 3. Replace CLIENT SCRIPT
        // ============================================================
        var newClient = 'function($scope, spUtil) {\n'
            + '  var c = this;\n'
            + '  c.mustInput = "";\n'
            + '  c.niceInput = "";\n'
            + '  c.mustSuggestions = [];\n'
            + '  c.niceSuggestions = [];\n'
            + '  c.mustChips = [];\n'
            + '  c.niceChips = [];\n'
            + '  c.searched = false;\n'
            + '  c.loading = false;\n'
            + '  c.results = [];\n'
            + '\n'
            + '  var searchTimer = null;\n'
            + '\n'
            + '  c.typeaheadSearch = function(which) {\n'
            + '    var term = (which == "must") ? c.mustInput : c.niceInput;\n'
            + '    if (searchTimer) clearTimeout(searchTimer);\n'
            + '    if (!term || term.length < 2) {\n'
            + '      if (which == "must") c.mustSuggestions = [];\n'
            + '      else c.niceSuggestions = [];\n'
            + '      return;\n'
            + '    }\n'
            + '    searchTimer = setTimeout(function() {\n'
            + '      c.server.get({ action: "searchSkills", term: term }).then(function(r) {\n'
            + '        var list = r.data.skillSuggestions || [];\n'
            + '        // Filter out already-selected chips\n'
            + '        var existing = c.mustChips.concat(c.niceChips);\n'
            + '        var filtered = [];\n'
            + '        for (var i = 0; i < list.length; i++) {\n'
            + '          if (existing.indexOf(list[i]) == -1) filtered.push(list[i]);\n'
            + '        }\n'
            + '        if (which == "must") c.mustSuggestions = filtered;\n'
            + '        else c.niceSuggestions = filtered;\n'
            + '        $scope.$applyAsync();\n'
            + '      });\n'
            + '    }, 300);\n'
            + '  };\n'
            + '\n'
            + '  c.selectSkill = function(which, name) {\n'
            + '    if (which == "must") {\n'
            + '      if (c.mustChips.indexOf(name) == -1) c.mustChips.push(name);\n'
            + '      c.mustInput = "";\n'
            + '      c.mustSuggestions = [];\n'
            + '    } else {\n'
            + '      if (c.niceChips.indexOf(name) == -1) c.niceChips.push(name);\n'
            + '      c.niceInput = "";\n'
            + '      c.niceSuggestions = [];\n'
            + '    }\n'
            + '  };\n'
            + '\n'
            + '  c.removeChip = function(which, idx) {\n'
            + '    if (which == "must") c.mustChips.splice(idx, 1);\n'
            + '    else c.niceChips.splice(idx, 1);\n'
            + '  };\n'
            + '\n'
            + '  c.search = function() {\n'
            + '    if (c.mustChips.length == 0 && c.niceChips.length == 0) return;\n'
            + '    c.loading = true;\n'
            + '    c.searched = true;\n'
            + '    c.results = [];\n'
            + '    c.server.get({\n'
            + '      action: "search",\n'
            + '      mustHave: c.mustChips.join(","),\n'
            + '      niceHave: c.niceChips.join(",")\n'
            + '    }).then(function(r) {\n'
            + '      c.loading = false;\n'
            + '      c.results = r.data.matches || [];\n'
            + '    });\n'
            + '  };\n'
            + '\n'
            + '  c.getScoreClass = function(score) {\n'
            + '    if (score >= 90) return "score-high";\n'
            + '    if (score >= 70) return "score-med";\n'
            + '    return "score-low";\n'
            + '  };\n'
            + '\n'
            + '  c.endorse = function(expert, entry) {\n'
            + '    if (!entry || !entry.skill_record_id) {\n'
            + '      spUtil.addInfoMessage("Endorsement not available for this entry.");\n'
            + '      return;\n'
            + '    }\n'
            + '    c.server.get({\n'
            + '      action: "endorse",\n'
            + '      skill_record_id: entry.skill_record_id\n'
            + '    }).then(function(r) {\n'
            + '      if (r.data.endorsed) {\n'
            + '        spUtil.addInfoMessage("Endorsed " + expert.name + "!");\n'
            + '      } else if (r.data.endorseError) {\n'
            + '        spUtil.addErrorMessage(r.data.endorseError);\n'
            + '      }\n'
            + '    });\n'
            + '  };\n'
            + '}\n';

        widgetGR = new GlideRecord('sp_widget');
        widgetGR.get(widgetId);
        widgetGR.setValue('client_script', newClient);
        widgetGR.update();
        gs.info('[Skills Hub] Client script replaced with typeahead + chip selection');

        // ============================================================
        // 4. Add CSS for typeahead, chips, and grouped results
        // ============================================================
        widgetGR = new GlideRecord('sp_widget');
        widgetGR.get(widgetId);
        var existingCSS = widgetGR.getValue('css') || '';

        var newCSS = '\n/* --- 36: Typeahead + Grouped Results --- */\n'
            + '.typeahead-dropdown {\n'
            + '  position: absolute; z-index: 1000; background: #fff; border: 1px solid #e2e8f0;\n'
            + '  border-radius: 6px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); max-height: 200px;\n'
            + '  overflow-y: auto; width: 100%; top: 100%; left: 0;\n'
            + '}\n'
            + '.typeahead-item {\n'
            + '  padding: 8px 12px; cursor: pointer; font-size: 13px;\n'
            + '}\n'
            + '.typeahead-item:hover { background: #f1f5f9; }\n'
            + '.chip-list { margin-top: 8px; display: flex; flex-wrap: wrap; gap: 6px; }\n'
            + '.skill-chip {\n'
            + '  background: #dbeafe; color: #1e40af; padding: 4px 10px; border-radius: 16px;\n'
            + '  font-size: 12px; display: inline-flex; align-items: center; gap: 6px;\n'
            + '}\n'
            + '.skill-chip.nice { background: #e0e7ff; color: #4338ca; }\n'
            + '.skill-chip i { cursor: pointer; font-size: 10px; }\n'
            + '.skill-chip i:hover { color: #dc2626; }\n'
            + '.results-grid { margin-top: 20px; }\n'
            + '.expert-card {\n'
            + '  background: #fff; border: 1px solid #e2e8f0; border-radius: 8px;\n'
            + '  padding: 16px; margin-bottom: 12px;\n'
            + '}\n'
            + '.expert-header { display: flex; align-items: center; gap: 12px; margin-bottom: 12px; }\n'
            + '.avatar-circle {\n'
            + '  width: 40px; height: 40px; border-radius: 50%; background: #3b82f6; color: #fff;\n'
            + '  display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 14px;\n'
            + '}\n'
            + '.expert-info { flex: 1; }\n'
            + '.expert-name { font-weight: 600; font-size: 14px; }\n'
            + '.expert-title { font-size: 12px; color: #64748b; }\n'
            + '.match-score {\n'
            + '  font-weight: 700; font-size: 18px; padding: 4px 10px; border-radius: 6px;\n'
            + '}\n'
            + '.score-high { background: #dcfce7; color: #15803d; }\n'
            + '.score-med { background: #fef9c3; color: #a16207; }\n'
            + '.score-low { background: #fee2e2; color: #dc2626; }\n'
            + '.skill-group-row {\n'
            + '  border-top: 1px solid #f1f5f9; padding: 8px 0;\n'
            + '}\n'
            + '.sg-header { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }\n'
            + '.sg-name { font-weight: 600; font-size: 13px; }\n'
            + '.sg-must { color: #1e40af; }\n'
            + '.sg-avg { font-size: 12px; color: #64748b; }\n'
            + '.sg-entries { padding-left: 12px; }\n'
            + '.sg-entry {\n'
            + '  display: flex; align-items: center; gap: 8px; padding: 3px 0; font-size: 12px;\n'
            + '}\n'
            + '.sg-cat-path { color: #64748b; flex: 1; }\n'
            + '.sg-level { font-weight: 500; }\n'
            + '.endorsement-pill {\n'
            + '  background: #dbeafe; color: #1e40af; padding: 2px 8px; border-radius: 10px;\n'
            + '  font-size: 11px;\n'
            + '}\n';

        // Append new CSS (don't replace - keep existing styles)
        widgetGR.setValue('css', existingCSS + newCSS);
        widgetGR.update();
        gs.info('[Skills Hub] CSS appended with typeahead + grouped result styles');

        gs.info('[Skills Hub] ===== SCRIPT 36 COMPLETE =====');

    } catch (e) {
        gs.error('[Skills Hub] Fatal error in script 36: ' + e.message);
    }
})();
