// ==========================================================
// Phase 1: Create Skill Categories (parent + child groups)
// Table: cmn_skill_category
// Run in: Scripts - Background (Global scope)
// ==========================================================

var LOG = 'SkillsSeed-Phase1';
var stats = { parents: 0, children: 0 };

function findOrCreate(table, query, fields) {
    var gr = new GlideRecord(table);
    gr.addEncodedQuery(query);
    gr.query();
    if (gr.next()) return gr.getUniqueValue();
    gr.initialize();
    for (var f in fields) gr.setValue(f, fields[f]);
    return gr.insert();
}

// --- Top-level categories ---
var catMap = {};
catMap['Epic Access'] = findOrCreate('cmn_skill_category', 'name=Epic Access^parentISEMPTY', { name: 'Epic Access' });
stats.parents++;
catMap['Epic Clinical'] = findOrCreate('cmn_skill_category', 'name=Epic Clinical^parentISEMPTY', { name: 'Epic Clinical' });
stats.parents++;
catMap['Epic Patient Access'] = findOrCreate('cmn_skill_category', 'name=Epic Patient Access^parentISEMPTY', { name: 'Epic Patient Access' });
stats.parents++;
catMap['Epic Revenue Cycle'] = findOrCreate('cmn_skill_category', 'name=Epic Revenue Cycle^parentISEMPTY', { name: 'Epic Revenue Cycle' });
stats.parents++;
catMap['Epic Technical'] = findOrCreate('cmn_skill_category', 'name=Epic Technical^parentISEMPTY', { name: 'Epic Technical' });
stats.parents++;
catMap['Governance'] = findOrCreate('cmn_skill_category', 'name=Governance^parentISEMPTY', { name: 'Governance' });
stats.parents++;
catMap['Leadership'] = findOrCreate('cmn_skill_category', 'name=Leadership^parentISEMPTY', { name: 'Leadership' });
stats.parents++;
catMap['Microsoft Technical'] = findOrCreate('cmn_skill_category', 'name=Microsoft Technical^parentISEMPTY', { name: 'Microsoft Technical' });
stats.parents++;
catMap['Professional Skills'] = findOrCreate('cmn_skill_category', 'name=Professional Skills^parentISEMPTY', { name: 'Professional Skills' });
stats.parents++;
catMap['Project Management'] = findOrCreate('cmn_skill_category', 'name=Project Management^parentISEMPTY', { name: 'Project Management' });
stats.parents++;

gs.info(LOG + ': Created ' + stats.parents + ' top-level categories');

// --- Child categories (skill groups) with parent reference ---
var groupMap = {};

groupMap['Epic Access::Cadence'] = findOrCreate('cmn_skill_category', 'name=Cadence^parent=' + catMap['Epic Access'], { name: 'Cadence', parent: catMap['Epic Access'] });
stats.children++;
groupMap['Epic Clinical::ASAP'] = findOrCreate('cmn_skill_category', 'name=ASAP^parent=' + catMap['Epic Clinical'], { name: 'ASAP', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Ambulatory'] = findOrCreate('cmn_skill_category', 'name=Ambulatory^parent=' + catMap['Epic Clinical'], { name: 'Ambulatory', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Ambulatory / Inpatient'] = findOrCreate('cmn_skill_category', 'name=Ambulatory / Inpatient^parent=' + catMap['Epic Clinical'], { name: 'Ambulatory / Inpatient', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Anesthesia'] = findOrCreate('cmn_skill_category', 'name=Anesthesia^parent=' + catMap['Epic Clinical'], { name: 'Anesthesia', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Beacon'] = findOrCreate('cmn_skill_category', 'name=Beacon^parent=' + catMap['Epic Clinical'], { name: 'Beacon', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Beaker'] = findOrCreate('cmn_skill_category', 'name=Beaker^parent=' + catMap['Epic Clinical'], { name: 'Beaker', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Beaker / Genomics'] = findOrCreate('cmn_skill_category', 'name=Beaker / Genomics^parent=' + catMap['Epic Clinical'], { name: 'Beaker / Genomics', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Community Connect'] = findOrCreate('cmn_skill_category', 'name=Community Connect^parent=' + catMap['Epic Clinical'], { name: 'Community Connect', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Connected Care'] = findOrCreate('cmn_skill_category', 'name=Connected Care^parent=' + catMap['Epic Clinical'], { name: 'Connected Care', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::EpicLink'] = findOrCreate('cmn_skill_category', 'name=EpicLink^parent=' + catMap['Epic Clinical'], { name: 'EpicLink', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Genomics'] = findOrCreate('cmn_skill_category', 'name=Genomics^parent=' + catMap['Epic Clinical'], { name: 'Genomics', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Grand Central'] = findOrCreate('cmn_skill_category', 'name=Grand Central^parent=' + catMap['Epic Clinical'], { name: 'Grand Central', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Inpatient'] = findOrCreate('cmn_skill_category', 'name=Inpatient^parent=' + catMap['Epic Clinical'], { name: 'Inpatient', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Interoperability'] = findOrCreate('cmn_skill_category', 'name=Interoperability^parent=' + catMap['Epic Clinical'], { name: 'Interoperability', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Kaleidoscope'] = findOrCreate('cmn_skill_category', 'name=Kaleidoscope^parent=' + catMap['Epic Clinical'], { name: 'Kaleidoscope', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Lumens'] = findOrCreate('cmn_skill_category', 'name=Lumens^parent=' + catMap['Epic Clinical'], { name: 'Lumens', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Mobile Apps'] = findOrCreate('cmn_skill_category', 'name=Mobile Apps^parent=' + catMap['Epic Clinical'], { name: 'Mobile Apps', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Optime'] = findOrCreate('cmn_skill_category', 'name=Optime^parent=' + catMap['Epic Clinical'], { name: 'Optime', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Optime, Cupid'] = findOrCreate('cmn_skill_category', 'name=Optime, Cupid^parent=' + catMap['Epic Clinical'], { name: 'Optime, Cupid', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Patient Entered Data'] = findOrCreate('cmn_skill_category', 'name=Patient Entered Data^parent=' + catMap['Epic Clinical'], { name: 'Patient Entered Data', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Pharmacy'] = findOrCreate('cmn_skill_category', 'name=Pharmacy^parent=' + catMap['Epic Clinical'], { name: 'Pharmacy', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Phoenix'] = findOrCreate('cmn_skill_category', 'name=Phoenix^parent=' + catMap['Epic Clinical'], { name: 'Phoenix', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Population Health'] = findOrCreate('cmn_skill_category', 'name=Population Health^parent=' + catMap['Epic Clinical'], { name: 'Population Health', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Quality Measures'] = findOrCreate('cmn_skill_category', 'name=Quality Measures^parent=' + catMap['Epic Clinical'], { name: 'Quality Measures', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Radiant/Cupid'] = findOrCreate('cmn_skill_category', 'name=Radiant/Cupid^parent=' + catMap['Epic Clinical'], { name: 'Radiant/Cupid', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Research'] = findOrCreate('cmn_skill_category', 'name=Research^parent=' + catMap['Epic Clinical'], { name: 'Research', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Specialty Apps'] = findOrCreate('cmn_skill_category', 'name=Specialty Apps^parent=' + catMap['Epic Clinical'], { name: 'Specialty Apps', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Stork'] = findOrCreate('cmn_skill_category', 'name=Stork^parent=' + catMap['Epic Clinical'], { name: 'Stork', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Clinical::Welcome'] = findOrCreate('cmn_skill_category', 'name=Welcome^parent=' + catMap['Epic Clinical'], { name: 'Welcome', parent: catMap['Epic Clinical'] });
stats.children++;
groupMap['Epic Patient Access::MyChart'] = findOrCreate('cmn_skill_category', 'name=MyChart^parent=' + catMap['Epic Patient Access'], { name: 'MyChart', parent: catMap['Epic Patient Access'] });
stats.children++;
groupMap['Epic Patient Access::Patient Access'] = findOrCreate('cmn_skill_category', 'name=Patient Access^parent=' + catMap['Epic Patient Access'], { name: 'Patient Access', parent: catMap['Epic Patient Access'] });
stats.children++;
groupMap['Epic Revenue Cycle::Charge router'] = findOrCreate('cmn_skill_category', 'name=Charge router^parent=' + catMap['Epic Revenue Cycle'], { name: 'Charge router', parent: catMap['Epic Revenue Cycle'] });
stats.children++;
groupMap['Epic Revenue Cycle::HIM'] = findOrCreate('cmn_skill_category', 'name=HIM^parent=' + catMap['Epic Revenue Cycle'], { name: 'HIM', parent: catMap['Epic Revenue Cycle'] });
stats.children++;
groupMap['Epic Revenue Cycle::Hospital Billing'] = findOrCreate('cmn_skill_category', 'name=Hospital Billing^parent=' + catMap['Epic Revenue Cycle'], { name: 'Hospital Billing', parent: catMap['Epic Revenue Cycle'] });
stats.children++;
groupMap['Epic Revenue Cycle::Hospital Billing/Professional Billing'] = findOrCreate('cmn_skill_category', 'name=Hospital Billing/Professional Billing^parent=' + catMap['Epic Revenue Cycle'], { name: 'Hospital Billing/Professional Billing', parent: catMap['Epic Revenue Cycle'] });
stats.children++;
groupMap['Epic Revenue Cycle::Patient Access'] = findOrCreate('cmn_skill_category', 'name=Patient Access^parent=' + catMap['Epic Revenue Cycle'], { name: 'Patient Access', parent: catMap['Epic Revenue Cycle'] });
stats.children++;
groupMap['Epic Revenue Cycle::Payer Management'] = findOrCreate('cmn_skill_category', 'name=Payer Management^parent=' + catMap['Epic Revenue Cycle'], { name: 'Payer Management', parent: catMap['Epic Revenue Cycle'] });
stats.children++;
groupMap['Epic Revenue Cycle::Professional Billing'] = findOrCreate('cmn_skill_category', 'name=Professional Billing^parent=' + catMap['Epic Revenue Cycle'], { name: 'Professional Billing', parent: catMap['Epic Revenue Cycle'] });
stats.children++;
groupMap['Epic Revenue Cycle::Resolute'] = findOrCreate('cmn_skill_category', 'name=Resolute^parent=' + catMap['Epic Revenue Cycle'], { name: 'Resolute', parent: catMap['Epic Revenue Cycle'] });
stats.children++;
groupMap['Epic Technical::Analytics'] = findOrCreate('cmn_skill_category', 'name=Analytics^parent=' + catMap['Epic Technical'], { name: 'Analytics', parent: catMap['Epic Technical'] });
stats.children++;
groupMap['Epic Technical::Batches'] = findOrCreate('cmn_skill_category', 'name=Batches^parent=' + catMap['Epic Technical'], { name: 'Batches', parent: catMap['Epic Technical'] });
stats.children++;
groupMap['Epic Technical::Campaigns'] = findOrCreate('cmn_skill_category', 'name=Campaigns^parent=' + catMap['Epic Technical'], { name: 'Campaigns', parent: catMap['Epic Technical'] });
stats.children++;
groupMap['Epic Technical::Epic Administration'] = findOrCreate('cmn_skill_category', 'name=Epic Administration^parent=' + catMap['Epic Technical'], { name: 'Epic Administration', parent: catMap['Epic Technical'] });
stats.children++;
groupMap['Epic Technical::Integration'] = findOrCreate('cmn_skill_category', 'name=Integration^parent=' + catMap['Epic Technical'], { name: 'Integration', parent: catMap['Epic Technical'] });
stats.children++;
groupMap['Epic Technical::Patient Engagement'] = findOrCreate('cmn_skill_category', 'name=Patient Engagement^parent=' + catMap['Epic Technical'], { name: 'Patient Engagement', parent: catMap['Epic Technical'] });
stats.children++;
groupMap['Epic Technical::Printing'] = findOrCreate('cmn_skill_category', 'name=Printing^parent=' + catMap['Epic Technical'], { name: 'Printing', parent: catMap['Epic Technical'] });
stats.children++;
groupMap['Epic Technical::System Admin'] = findOrCreate('cmn_skill_category', 'name=System Admin^parent=' + catMap['Epic Technical'], { name: 'System Admin', parent: catMap['Epic Technical'] });
stats.children++;
groupMap['Governance::FAC/ORG'] = findOrCreate('cmn_skill_category', 'name=FAC/ORG^parent=' + catMap['Governance'], { name: 'FAC/ORG', parent: catMap['Governance'] });
stats.children++;
groupMap['Governance::Front End Steering'] = findOrCreate('cmn_skill_category', 'name=Front End Steering^parent=' + catMap['Governance'], { name: 'Front End Steering', parent: catMap['Governance'] });
stats.children++;
groupMap['Governance::Patient Communication'] = findOrCreate('cmn_skill_category', 'name=Patient Communication^parent=' + catMap['Governance'], { name: 'Patient Communication', parent: catMap['Governance'] });
stats.children++;
groupMap['Leadership::Change Management'] = findOrCreate('cmn_skill_category', 'name=Change Management^parent=' + catMap['Leadership'], { name: 'Change Management', parent: catMap['Leadership'] });
stats.children++;
groupMap['Leadership::Operational Transition'] = findOrCreate('cmn_skill_category', 'name=Operational Transition^parent=' + catMap['Leadership'], { name: 'Operational Transition', parent: catMap['Leadership'] });
stats.children++;
groupMap['Leadership::Stakeholder Partnership'] = findOrCreate('cmn_skill_category', 'name=Stakeholder Partnership^parent=' + catMap['Leadership'], { name: 'Stakeholder Partnership', parent: catMap['Leadership'] });
stats.children++;
groupMap['Leadership::Team Leadership'] = findOrCreate('cmn_skill_category', 'name=Team Leadership^parent=' + catMap['Leadership'], { name: 'Team Leadership', parent: catMap['Leadership'] });
stats.children++;
groupMap['Microsoft Technical::Azure Chat'] = findOrCreate('cmn_skill_category', 'name=Azure Chat^parent=' + catMap['Microsoft Technical'], { name: 'Azure Chat', parent: catMap['Microsoft Technical'] });
stats.children++;
groupMap['Microsoft Technical::CRM'] = findOrCreate('cmn_skill_category', 'name=CRM^parent=' + catMap['Microsoft Technical'], { name: 'CRM', parent: catMap['Microsoft Technical'] });
stats.children++;
groupMap['Professional Skills::Certifications'] = findOrCreate('cmn_skill_category', 'name=Certifications^parent=' + catMap['Professional Skills'], { name: 'Certifications', parent: catMap['Professional Skills'] });
stats.children++;
groupMap['Professional Skills::Collaboration Tools'] = findOrCreate('cmn_skill_category', 'name=Collaboration Tools^parent=' + catMap['Professional Skills'], { name: 'Collaboration Tools', parent: catMap['Professional Skills'] });
stats.children++;
groupMap['Professional Skills::Domain Knowledge'] = findOrCreate('cmn_skill_category', 'name=Domain Knowledge^parent=' + catMap['Professional Skills'], { name: 'Domain Knowledge', parent: catMap['Professional Skills'] });
stats.children++;
groupMap['Professional Skills::ITSM Platform'] = findOrCreate('cmn_skill_category', 'name=ITSM Platform^parent=' + catMap['Professional Skills'], { name: 'ITSM Platform', parent: catMap['Professional Skills'] });
stats.children++;
groupMap['Professional Skills::Productivity Suite'] = findOrCreate('cmn_skill_category', 'name=Productivity Suite^parent=' + catMap['Professional Skills'], { name: 'Productivity Suite', parent: catMap['Professional Skills'] });
stats.children++;
groupMap['Project Management::Budget'] = findOrCreate('cmn_skill_category', 'name=Budget^parent=' + catMap['Project Management'], { name: 'Budget', parent: catMap['Project Management'] });
stats.children++;
groupMap['Project Management::Communication'] = findOrCreate('cmn_skill_category', 'name=Communication^parent=' + catMap['Project Management'], { name: 'Communication', parent: catMap['Project Management'] });
stats.children++;
groupMap['Project Management::Quality'] = findOrCreate('cmn_skill_category', 'name=Quality^parent=' + catMap['Project Management'], { name: 'Quality', parent: catMap['Project Management'] });
stats.children++;
groupMap['Project Management::Risk'] = findOrCreate('cmn_skill_category', 'name=Risk^parent=' + catMap['Project Management'], { name: 'Risk', parent: catMap['Project Management'] });
stats.children++;
groupMap['Project Management::Schedule'] = findOrCreate('cmn_skill_category', 'name=Schedule^parent=' + catMap['Project Management'], { name: 'Schedule', parent: catMap['Project Management'] });
stats.children++;
groupMap['Project Management::Scope'] = findOrCreate('cmn_skill_category', 'name=Scope^parent=' + catMap['Project Management'], { name: 'Scope', parent: catMap['Project Management'] });
stats.children++;
groupMap['Project Management::Vendor'] = findOrCreate('cmn_skill_category', 'name=Vendor^parent=' + catMap['Project Management'], { name: 'Vendor', parent: catMap['Project Management'] });
stats.children++;

gs.info(LOG + ': Created ' + stats.children + ' child categories (skill groups)');
gs.info(LOG + ': Phase 1 complete. Save these sys_ids — Phase 2 needs them.');