// ==========================================================
// Phase 3 Batch 2: Link Skills for 'Epic Clinical'
// Table: cmn_skill_m2m_category
// Run in: Scripts - Background (Global scope)
// ==========================================================

var LOG = 'SkillsSeed-Phase3-EpicClinical';
var linked = 0;

function findSysId(table, query) {
    var gr = new GlideRecord(table);
    gr.addEncodedQuery(query);
    gr.query();
    if (gr.next()) return gr.getUniqueValue();
    return null;
}

function linkSkillToCategory(skillName, groupName, parentName) {
    var skillId = findSysId('cmn_skill', 'name=' + skillName);
    var parentId = findSysId('cmn_skill_category', 'name=' + parentName + '^parentISEMPTY');
    if (!parentId) { gs.warn(LOG + ': Parent category not found: ' + parentName); return; }
    var groupId = findSysId('cmn_skill_category', 'name=' + groupName + '^parent=' + parentId);
    if (!skillId) { gs.warn(LOG + ': Skill not found: ' + skillName); return; }
    if (!groupId) { gs.warn(LOG + ': Group not found: ' + groupName + ' under ' + parentName); return; }
    // Check if link already exists
    var m2m = new GlideRecord('cmn_skill_m2m_category');
    m2m.addQuery('skill', skillId);
    m2m.addQuery('category', groupId);
    m2m.query();
    if (m2m.next()) return;
    m2m.initialize();
    m2m.setValue('skill', skillId);
    m2m.setValue('category', groupId);
    m2m.insert();
    linked++;
}

linkSkillToCategory('ASAP Configuration', 'ASAP', 'Epic Clinical');
linkSkillToCategory('Triage Workflows', 'ASAP', 'Epic Clinical');
linkSkillToCategory('Fast Track/Urgent Care', 'ASAP', 'Epic Clinical');
linkSkillToCategory('Security Liason', 'ASAP', 'Epic Clinical');
linkSkillToCategory('ED Manager', 'ASAP', 'Epic Clinical');
linkSkillToCategory('ED Trackboard', 'ASAP', 'Epic Clinical');
linkSkillToCategory('SmartTools', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Discrete Value', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Visit Workflows', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('E-Prescribing', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('MyChart', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('WFE Rules', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Navigator Build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('AVS Maintenances', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Updates to Base Profile [1000]', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Updates to LSD', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Programming Points Creation and Maintenance', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Rule Creation', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('SmartForms/ProcDoc Build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Department Updates', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Printer Mapping', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Encounter Conversion', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('LOS', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Psych Build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Note Build (Shared; Sensitive)', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('AI Notes', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Clinic Map build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Track Board build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Storyboard build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Ortho (Bones)', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Wisdom', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Urgent Care', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Nurse Triage', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Comm Manager', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Orders', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Create Pools', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Reports and Print Group build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('FHIR Application build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('ECONSULTS', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Anticoag Build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Immunization', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Medication Administration', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Bridges/Interfaces', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Therapy Plans', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Clarity and Reporting', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Imports/Exports', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Reporting Dashboard', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Profiles', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Category List mainenace', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Data Courier', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Question build', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Chronicles usage', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('OPA\'s', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Security & Access', 'Ambulatory', 'Epic Clinical');
linkSkillToCategory('Order Transmittal', 'Ambulatory / Inpatient', 'Epic Clinical');
linkSkillToCategory('Inpatient Second Sign Rule', 'Ambulatory / Inpatient', 'Epic Clinical');
linkSkillToCategory('Anesthesia', 'Anesthesia', 'Epic Clinical');
linkSkillToCategory('Oncology build and  Workflows', 'Beacon', 'Epic Clinical');
linkSkillToCategory('BMT build and workflows', 'Beacon', 'Epic Clinical');
linkSkillToCategory('Apheresis build and workflows', 'Beacon', 'Epic Clinical');
linkSkillToCategory('Schedulable orders', 'Beacon', 'Epic Clinical');
linkSkillToCategory('Referral workqueue', 'Beacon', 'Epic Clinical');
linkSkillToCategory('Therapy Plan build and workflows', 'Beacon', 'Epic Clinical');
linkSkillToCategory('Synopsis Build', 'Beacon', 'Epic Clinical');
linkSkillToCategory('Survivorship workflow', 'Beacon', 'Epic Clinical');
linkSkillToCategory('Care Path build and workflows', 'Beacon', 'Epic Clinical');
linkSkillToCategory('Cancer Staging workflows', 'Beacon', 'Epic Clinical');
linkSkillToCategory('External lab vendor integrations', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Lab Orders & Results', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Outpatient Specimen collection workflows', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Inpatient Specimen collection workflows', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Print groups and Report', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Interfaced lab workflows', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Lab charge messages', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Microbiology workflows', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Blood Bank/Transfusion workflows', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Lab order transmittal', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Lab Result routing schemes', 'Beaker', 'Epic Clinical');
linkSkillToCategory('External client workflows', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Anatomic Pathology', 'Beaker', 'Epic Clinical');
linkSkillToCategory('Molecular diagnostic build and workflows', 'Beaker / Genomics', 'Epic Clinical');
linkSkillToCategory('Physician and Clinical Support', 'Community Connect', 'Epic Clinical');
linkSkillToCategory('Support Desk', 'Community Connect', 'Epic Clinical');
linkSkillToCategory('Technical Review', 'Community Connect', 'Epic Clinical');
linkSkillToCategory('Dorothy/Comfort', 'Connected Care', 'Epic Clinical');
linkSkillToCategory('Reporting Tools', 'Connected Care', 'Epic Clinical');
linkSkillToCategory('Scheduling', 'Connected Care', 'Epic Clinical');
linkSkillToCategory('Dr. Connect', 'EpicLink', 'Epic Clinical');
linkSkillToCategory('Genomic build and workflows', 'Genomics', 'Epic Clinical');
linkSkillToCategory('Logistics - Environmental Services', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Logistics - Transport', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Bed Planning', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Transfer Center', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Patient Movement (Admission, Transfer, Discharge)', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Bed Administration (Facility Structure, Departments, Rooms, Beds)', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('ADT Order Setup', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('ED, L&D, and Inpatient Registration', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Event Notifications', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('BCAWeb Configuration', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Hospital Care at Home', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Import/Export', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Forms', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('eSignature', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Batch Jobs, Batches, Runs', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Security Liason', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Reports', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Dashboards', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Data Courier', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('System Definitions (Facility, Service Area, Location)', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Wristbands', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Paging', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Printing', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Storyboard', 'Grand Central', 'Epic Clinical');
linkSkillToCategory('Clinical Documentation', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Order Management', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Medication Administration', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Discharge Planning', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Nursing Workflows', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Flowsheets, LDA Avatar', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('BPAs', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('ADT Orders', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Activity Therapy (BH Units only)', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Ambulance Services', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Art Therapy', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Ancillary Service Package (ASP)', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Audiology', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('BCA - Device Setup', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('BCA - Downtime Forms', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Behavioral Health IOP/PHP', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Biometrics', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('BPAM', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Cardiac Rehab', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Cardiology Orders', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Hospital Care at Home', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Care Management / Social Work', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Care Paths (Sepsis, Ortho, Stroke, DCRT)', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Child Life', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Clinical Decision Support', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Consents', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Consult Orders', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Core ClinDoc', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Core Orders', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Custom Coding', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Device Build', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Diabetes Education', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Doc Excellence', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('DT Orders Release and DT Reports', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('EEG', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Endoscopy Orders / Results / Workflows', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Epic Monitor', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Ethics / Biothics', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('eRX Setup', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Form Filler', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Form Reprints', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Haiku Push Notifications', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Healing Services / Hospice', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('IIT (ID Type) / LLP (Resulting Agencies)', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Import/Export', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('In Basket Pool / Results Routing', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Infection Prevention / Bugsy', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Inpatient Rehab Facility', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Intake SW/ED Triage Nurse', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Long Term Care', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('MR Screening Tool', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Music Therapy', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Navigators', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Nutrition Services', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Occupational Therapy', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Order Error Correction', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Order Sets', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Order Set Restrictors', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Orders Interface / Results Interface', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Palantir', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Physical Therapy', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('PICC', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('POC Tests', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Print Group Based Reports', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Printing Setup', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Profiles', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Pulmonary Function Lab', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Pulmonary Rehab', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Quality', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Radiology Orders', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Rehab Module', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Reporting - Chronicles', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Reporting - Crystal Reports / Clarity SQL', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Reporting - Network Search', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Reporting - Orders Report Program', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Reporting - Slicer Dicer', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Reporting - Reporting Workbench', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Respiratory Therapy', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('SANE (Sexual Assault Nurse)', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Security Liason', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('SmartForm / PROC Doc', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Speech Therapy', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Spiritual Care (Pastoral Care)', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Storyboard', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('System Lists', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Treatment Teams', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Workflow Engine Rules', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Wound / ET Stoma / Skin Care', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('Behavioral Health', 'Inpatient', 'Epic Clinical');
linkSkillToCategory('CareEverywhere', 'Interoperability', 'Epic Clinical');
linkSkillToCategory('Ophthalmology build and workflows', 'Kaleidoscope', 'Epic Clinical');
linkSkillToCategory('Endoscopy narrator', 'Lumens', 'Epic Clinical');
linkSkillToCategory('Endoscopy structured reporting', 'Lumens', 'Epic Clinical');
linkSkillToCategory('Endoscopy charging', 'Lumens', 'Epic Clinical');
linkSkillToCategory('Endoscopy scheduling', 'Lumens', 'Epic Clinical');
linkSkillToCategory('Secure Chat group build', 'Mobile Apps', 'Epic Clinical');
linkSkillToCategory('Rover set up and workflows', 'Mobile Apps', 'Epic Clinical');
linkSkillToCategory('Haiku set up and workflows', 'Mobile Apps', 'Epic Clinical');
linkSkillToCategory('Haiku BYOD set up', 'Mobile Apps', 'Epic Clinical');
linkSkillToCategory('OpTime Scheduling', 'Optime', 'Epic Clinical');
linkSkillToCategory('Intraoperative Documentation', 'Optime', 'Epic Clinical');
linkSkillToCategory('Perioperative Workflows', 'Optime', 'Epic Clinical');
linkSkillToCategory('Procedural Areas', 'Optime, Cupid', 'Epic Clinical');
linkSkillToCategory('Optime charging and billing', 'Optime, Cupid', 'Epic Clinical');
linkSkillToCategory('Questionnaires build and workflows', 'Patient Entered Data', 'Epic Clinical');
linkSkillToCategory('Willow Ambulatory', 'Pharmacy', 'Epic Clinical');
linkSkillToCategory('Inventory Management', 'Pharmacy', 'Epic Clinical');
linkSkillToCategory('Clinical Decision Support', 'Pharmacy', 'Epic Clinical');
linkSkillToCategory('Oncology workflows', 'Pharmacy', 'Epic Clinical');
linkSkillToCategory('Transplant build and workflows', 'Phoenix', 'Epic Clinical');
linkSkillToCategory('Healthy Planet Core', 'Population Health', 'Epic Clinical');
linkSkillToCategory('Compass Rose', 'Population Health', 'Epic Clinical');
linkSkillToCategory('HCC Care Gaps', 'Population Health', 'Epic Clinical');
linkSkillToCategory('Payor Platform', 'Population Health', 'Epic Clinical');
linkSkillToCategory('Quality Measures', 'Quality Measures', 'Epic Clinical');
linkSkillToCategory('Imaging technologist and radiologist workflow', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Cardiology technologist and cardiologist workflow', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Imaging (radiology) orders & results', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Imaging scheduling', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Imaging invasive & IR Procedures', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Cardiology studies', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Cardiology Invasive Procedures', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Imaging Charging and Billing', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Actionable findings', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Breast imaging', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('DICOM', 'Radiant/Cupid', 'Epic Clinical');
linkSkillToCategory('Research', 'Research', 'Epic Clinical');
linkSkillToCategory('Storyboard build', 'Specialty Apps', 'Epic Clinical');
linkSkillToCategory('OB (Stork)', 'Specialty Apps', 'Epic Clinical');
linkSkillToCategory('Rehab', 'Specialty Apps', 'Epic Clinical');
linkSkillToCategory('L&D Manager', 'Stork', 'Epic Clinical');
linkSkillToCategory('L&D Greaseboard', 'Stork', 'Epic Clinical');
linkSkillToCategory('Welcome workflows', 'Welcome', 'Epic Clinical');
linkSkillToCategory('Welcome Web', 'Welcome', 'Epic Clinical');
linkSkillToCategory('Welcome eConsent', 'Welcome', 'Epic Clinical');
linkSkillToCategory('Welcome Tablets', 'Welcome', 'Epic Clinical');

gs.info(LOG + ': Linked ' + linked + ' skills to groups under Epic Clinical');